language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
script:
    - "python src/splatfilch.py update -s -vvv"
notifications:
    irc:
        channels:
            - "chat.freenode.net#splatfilch"
            - "irc.cat.pdx.edu#splatfilch"
